/* This file was generated by the Hex-Rays decompiler version 8.4.0.240320.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall sub_180001000(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall sub_1800010D0(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall JNI_OnLoad(__int64 a1);
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_GetVersionLib(__int64 a1);
__int64 Java_br_uol_pagseguro_client_plugpag_PlugPag_InitBTConnection__();
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_InitBTConnection__Ljava_lang_String_2(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_SimplePaymentTransaction(__int64 a1, __int64 a2, unsigned int a3, unsigned int a4, unsigned int a5, __int64 a6, __int64 a7);
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_CancelTransaction(__int64 a1, __int64 a2);
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_GetLastApprovedTransactionStatus(__int64 a1, __int64 a2);
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_SetVersionName(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
char sub_180001F94();
void sub_1800023B8();
void __fastcall sub_1800023C8();
void *sub_1800023D4();
void *sub_1800023DC();
void *sub_180002400();
__int64 sub_180002550();
void __fastcall sub_18000259C();
__int64 __fastcall j__guard_check_icall_nop(); // weak
// __int64 __fastcall _std_type_info_destroy_list(_QWORD); weak
// void *__cdecl memset(void *, int Val, size_t Size);
char sub_180002824();
__int64 sub_180002828();
// __int64 __fastcall CancelTransaction(_QWORD); weak
// __int64 __fastcall SetVersionName(_QWORD, _QWORD); weak
// __int64 __fastcall InitBTConnection(_QWORD); weak
// __int64 GetVersionLib(void); weak
// __int64 __fastcall GetLastApprovedTransactionStatus(_QWORD); weak
// __int64 __fastcall SimplePaymentTransaction(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

// extern void (__stdcall *InitializeSListHead)(PSLIST_HEADER ListHead);
_QWORD qword_180003630[2] = { 0LL, 0LL }; // weak
_QWORD qword_180003640 = 0LL; // weak
union _SLIST_HEADER stru_180005610; // weak
_UNKNOWN unk_180005620; // weak
_UNKNOWN unk_180005628; // weak
__int64 qword_180005638; // weak
_UNKNOWN unk_180005640; // weak
__int64 qword_180005648; // weak


//----- (0000000180001000) ----------------------------------------------------
__int64 __fastcall sub_180001000(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v8; // rdi
  __int64 v9; // r9

  qword_180005638 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)a1 + 248LL))(a1);
  if ( !qword_180005638 )
    return 4294964296LL;
  v8 = (*(__int64 (__fastcall **)(__int64, __int64, __int64, const char *))(*(_QWORD *)a1 + 752LL))(
         a1,
         qword_180005638,
         a3,
         "Ljava/lang/String;");
  if ( !v8 )
    return 4294964296LL;
  v9 = (*(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)a1 + 1336LL))(a1, a4);
  if ( !v9 )
    return 4294964296LL;
  (*(void (__fastcall **)(__int64, __int64, __int64, __int64))(*(_QWORD *)a1 + 832LL))(a1, a2, v8, v9);
  if ( (*(unsigned __int8 (__fastcall **)(__int64))(*(_QWORD *)qword_180005648 + 1824LL))(qword_180005648) )
  {
    (*(void (__fastcall **)(__int64))(*(_QWORD *)qword_180005648 + 136LL))(qword_180005648);
    return 4294964296LL;
  }
  return 0LL;
}
// 180005638: using guessed type __int64 qword_180005638;
// 180005648: using guessed type __int64 qword_180005648;

//----- (00000001800010D0) ----------------------------------------------------
__int64 __fastcall sub_1800010D0(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v8; // rsi
  __int64 v9; // rdi

  qword_180005638 = (*(__int64 (__fastcall **)(__int64))(*(_QWORD *)a1 + 248LL))(a1);
  if ( !qword_180005638 )
    return 4294964296LL;
  v8 = (*(__int64 (__fastcall **)(__int64, __int64, const char *, const char *))(*(_QWORD *)a1 + 752LL))(
         a1,
         qword_180005638,
         "rawBuffer",
         "[B");
  if ( !v8 )
    return 4294964296LL;
  v9 = (*(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)a1 + 1408LL))(a1, 65542LL);
  if ( !v9 )
    return 4294964296LL;
  (*(void (__fastcall **)(__int64, __int64, _QWORD, __int64, __int64))(*(_QWORD *)a1 + 1664LL))(
    a1,
    v9,
    0LL,
    65542LL,
    a4);
  if ( (*(unsigned __int8 (__fastcall **)(__int64))(*(_QWORD *)qword_180005648 + 1824LL))(qword_180005648)
    || ((*(void (__fastcall **)(__int64, __int64, __int64, __int64))(*(_QWORD *)a1 + 832LL))(a1, a2, v8, v9),
        (*(unsigned __int8 (__fastcall **)(__int64))(*(_QWORD *)qword_180005648 + 1824LL))(qword_180005648)) )
  {
    (*(void (__fastcall **)(__int64))(*(_QWORD *)qword_180005648 + 136LL))(qword_180005648);
    return 4294964296LL;
  }
  return 0LL;
}
// 180005638: using guessed type __int64 qword_180005638;
// 180005648: using guessed type __int64 qword_180005648;

//----- (0000000180001200) ----------------------------------------------------
__int64 __fastcall JNI_OnLoad(__int64 a1)
{
  __int64 result; // rax
  __int64 v2; // [rsp+20h] [rbp-18h] BYREF

  if ( (*(unsigned int (__fastcall **)(__int64, __int64 *, __int64))(*(_QWORD *)a1 + 48LL))(a1, &v2, 65542LL) )
    return 4294964296LL;
  result = 65542LL;
  qword_180005648 = v2;
  return result;
}
// 180005648: using guessed type __int64 qword_180005648;

//----- (0000000180001270) ----------------------------------------------------
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_GetVersionLib(__int64 a1)
{
  __int64 VersionLib; // rax

  VersionLib = GetVersionLib();
  return (*(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)a1 + 1336LL))(a1, VersionLib);
}
// 1800030A0: using guessed type __int64 GetVersionLib(void);

//----- (00000001800012B0) ----------------------------------------------------
__int64 Java_br_uol_pagseguro_client_plugpag_PlugPag_InitBTConnection__()
{
  return InitBTConnection(0LL);
}
// 180003098: using guessed type __int64 __fastcall InitBTConnection(_QWORD);

//----- (00000001800012C0) ----------------------------------------------------
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_InitBTConnection__Ljava_lang_String_2(
        __int64 a1,
        __int64 a2,
        __int64 a3)
{
  __int64 v5; // rbx
  unsigned int inited; // edi

  v5 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(*(_QWORD *)a1 + 1352LL))(a1, a3, 0LL);
  inited = InitBTConnection(v5);
  (*(void (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 1360LL))(a1, a3, v5);
  return inited;
}
// 180003098: using guessed type __int64 __fastcall InitBTConnection(_QWORD);

//----- (0000000180001330) ----------------------------------------------------
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_SimplePaymentTransaction(
        __int64 a1,
        __int64 a2,
        unsigned int a3,
        unsigned int a4,
        unsigned int a5,
        __int64 a6,
        __int64 a7)
{
  __int64 v8; // rdi
  __int64 v11; // r12
  __int64 v12; // r15
  unsigned int v13; // r13d
  __int64 *i; // rbx
  __int64 v15; // r8
  char *v18; // [rsp+40h] [rbp-C0h]
  __int64 v19[19]; // [rsp+48h] [rbp-B8h] BYREF
  char v20[66768]; // [rsp+E0h] [rbp-20h] BYREF

  v18 = &v20[66664];
  v19[0] = (__int64)"bin";
  v8 = 0LL;
  v19[1] = (__int64)&v20[66633];
  v19[2] = (__int64)"cardBrand";
  v19[3] = (__int64)&v20[66600];
  v19[4] = (__int64)"date";
  v19[5] = (__int64)&v20[66671];
  v19[6] = (__int64)"holder";
  v19[7] = (__int64)&v20[66620];
  v19[8] = (__int64)"hostNsu";
  v19[9] = (__int64)&v20[66611];
  v19[10] = (__int64)"time";
  v19[11] = (__int64)&v20[66676];
  v19[12] = (__int64)"userReference";
  v19[13] = (__int64)&v20[66567];
  v19[14] = (__int64)"transactionCode";
  v19[15] = (__int64)&v20[65543];
  v19[16] = (__int64)"message";
  v19[17] = (__int64)&v20[66687];
  v19[18] = (__int64)"terminalSerialNumber";
  if ( a6 )
    v11 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(*(_QWORD *)a1 + 1352LL))(a1, a6, 0LL);
  else
    v11 = 0LL;
  if ( a7 )
    v12 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(*(_QWORD *)a1 + 1352LL))(a1, a7, 0LL);
  else
    v12 = 0LL;
  memset(v20, 0, 0x104C1uLL);
  v13 = SimplePaymentTransaction(a3, a4, a5, v11, v12, v20);
  if ( a6 )
    (*(void (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 1360LL))(a1, a6, v11);
  if ( a7 )
    (*(void (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 1360LL))(a1, a7, v12);
  if ( v13 )
    return v13;
  for ( i = v19; (int)sub_180001000(a1, a2, *i, *(i - 1)) >= 0; i += 2 )
  {
    if ( ++v8 >= 10 )
    {
      if ( (int)sub_1800010D0(a1, a2, v15, (__int64)v20) >= 0 )
        return v13;
      return 4294964296LL;
    }
  }
  return 4294964296LL;
}
// 18000154D: variable 'v15' is possibly undefined
// 1800030B0: using guessed type __int64 __fastcall SimplePaymentTransaction(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000180001590) ----------------------------------------------------
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_CancelTransaction(__int64 a1, __int64 a2)
{
  unsigned int v4; // r15d
  __int64 v5; // rdi
  __int64 *i; // rbx
  __int64 v7; // r8
  char *v9; // [rsp+30h] [rbp-D0h]
  __int64 v10[19]; // [rsp+38h] [rbp-C8h] BYREF
  char v11[66768]; // [rsp+D0h] [rbp-30h] BYREF

  v9 = &v11[66664];
  v10[0] = (__int64)"bin";
  v10[1] = (__int64)&v11[66633];
  v10[2] = (__int64)"cardBrand";
  v10[3] = (__int64)&v11[66600];
  v10[4] = (__int64)"date";
  v10[5] = (__int64)&v11[66671];
  v10[6] = (__int64)"holder";
  v10[7] = (__int64)&v11[66620];
  v10[8] = (__int64)"hostNsu";
  v10[9] = (__int64)&v11[66611];
  v10[10] = (__int64)"time";
  v10[11] = (__int64)&v11[66676];
  v10[12] = (__int64)"userReference";
  v10[13] = (__int64)&v11[66567];
  v10[14] = (__int64)"transactionCode";
  v10[15] = (__int64)&v11[65543];
  v10[16] = (__int64)"message";
  v10[17] = (__int64)&v11[66687];
  v10[18] = (__int64)"terminalSerialNumber";
  memset(v11, 0, 0x104C1uLL);
  v4 = CancelTransaction(v11);
  if ( v4 )
    return v4;
  v5 = 0LL;
  for ( i = v10; (int)sub_180001000(a1, a2, *i, *(i - 1)) >= 0; i += 2 )
  {
    if ( ++v5 >= 10 )
    {
      if ( (int)sub_1800010D0(a1, a2, v7, (__int64)v11) >= 0 )
        return v4;
      return 4294964296LL;
    }
  }
  return 4294964296LL;
}
// 18000170D: variable 'v7' is possibly undefined
// 180003080: using guessed type __int64 __fastcall CancelTransaction(_QWORD);

//----- (0000000180001750) ----------------------------------------------------
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_GetLastApprovedTransactionStatus(
        __int64 a1,
        __int64 a2)
{
  unsigned int LastApprovedTransactionStatus; // r15d
  __int64 v5; // rdi
  __int64 *i; // rbx
  __int64 v7; // r8
  char *v9; // [rsp+30h] [rbp-D0h]
  __int64 v10[19]; // [rsp+38h] [rbp-C8h] BYREF
  char v11[65543]; // [rsp+D0h] [rbp-30h] BYREF
  char v12; // [rsp+100D7h] [rbp+FFD7h] BYREF
  char v13; // [rsp+104D7h] [rbp+103D7h] BYREF
  char v14; // [rsp+104F8h] [rbp+103F8h] BYREF
  char v15; // [rsp+10503h] [rbp+10403h] BYREF
  char v16; // [rsp+1050Ch] [rbp+1040Ch] BYREF
  char v17; // [rsp+10519h] [rbp+10419h] BYREF
  char v18; // [rsp+10538h] [rbp+10438h] BYREF
  char v19; // [rsp+1053Fh] [rbp+1043Fh] BYREF
  char v20; // [rsp+10544h] [rbp+10444h] BYREF
  char v21; // [rsp+1054Fh] [rbp+1044Fh] BYREF

  v9 = &v18;
  v10[0] = (__int64)"bin";
  v10[1] = (__int64)&v17;
  v10[2] = (__int64)"cardBrand";
  v10[3] = (__int64)&v14;
  v10[4] = (__int64)"date";
  v10[5] = (__int64)&v19;
  v10[6] = (__int64)"holder";
  v10[7] = (__int64)&v16;
  v10[8] = (__int64)"hostNsu";
  v10[9] = (__int64)&v15;
  v10[10] = (__int64)"time";
  v10[11] = (__int64)&v20;
  v10[12] = (__int64)"userReference";
  v10[13] = (__int64)&v13;
  v10[14] = (__int64)"transactionCode";
  v10[15] = (__int64)&v12;
  v10[16] = (__int64)"message";
  v10[17] = (__int64)&v21;
  v10[18] = (__int64)"terminalSerialNumber";
  LastApprovedTransactionStatus = GetLastApprovedTransactionStatus(v11);
  if ( LastApprovedTransactionStatus )
    return LastApprovedTransactionStatus;
  v5 = 0LL;
  for ( i = v10; (int)sub_180001000(a1, a2, *i, *(i - 1)) >= 0; i += 2 )
  {
    if ( ++v5 >= 10 )
    {
      if ( (int)sub_1800010D0(a1, a2, v7, (__int64)v11) >= 0 )
        return LastApprovedTransactionStatus;
      return 4294964296LL;
    }
  }
  return 4294964296LL;
}
// 1800018BD: variable 'v7' is possibly undefined
// 1800030A8: using guessed type __int64 __fastcall GetLastApprovedTransactionStatus(_QWORD);

//----- (0000000180001900) ----------------------------------------------------
__int64 __fastcall Java_br_uol_pagseguro_client_plugpag_PlugPag_SetVersionName(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4)
{
  __int64 v8; // r15
  __int64 v9; // rbx
  unsigned int v10; // edi

  if ( !a3 )
    return 4294966294LL;
  v8 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(*(_QWORD *)a1 + 1352LL))(a1, a3, 0LL);
  if ( !a4 )
    return 4294966294LL;
  v9 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(*(_QWORD *)a1 + 1352LL))(a1, a4, 0LL);
  v10 = SetVersionName(v8, v9);
  (*(void (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 1360LL))(a1, a3, v8);
  (*(void (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 1360LL))(a1, a4, v9);
  return v10;
}
// 180003090: using guessed type __int64 __fastcall SetVersionName(_QWORD, _QWORD);

//----- (0000000180001F94) ----------------------------------------------------
char sub_180001F94()
{
  if ( !sub_180002824() )
    return 0;
  if ( !sub_180002824() )
  {
    sub_180002824();
    return 0;
  }
  return 1;
}

//----- (00000001800023B8) ----------------------------------------------------
void sub_1800023B8()
{
  InitializeSListHead(&stru_180005610);
}
// 180005610: using guessed type union _SLIST_HEADER stru_180005610;

//----- (00000001800023C8) ----------------------------------------------------
void __fastcall sub_1800023C8()
{
  _std_type_info_destroy_list(&stru_180005610);
}
// 1800027D6: using guessed type __int64 __fastcall _std_type_info_destroy_list(_QWORD);
// 180005610: using guessed type union _SLIST_HEADER stru_180005610;

//----- (00000001800023D4) ----------------------------------------------------
void *sub_1800023D4()
{
  return &unk_180005620;
}

//----- (00000001800023DC) ----------------------------------------------------
void *sub_1800023DC()
{
  return &unk_180005628;
}

//----- (0000000180002400) ----------------------------------------------------
void *sub_180002400()
{
  return &unk_180005640;
}

//----- (0000000180002550) ----------------------------------------------------
__int64 sub_180002550()
{
  _QWORD *i; // rbx
  __int64 result; // rax

  for ( i = qword_180003630; i < qword_180003630; ++i )
  {
    if ( *i )
      result = ((__int64 (__fastcall *)(_QWORD))*i)(*i);
  }
  return result;
}
// 1800025E8: using guessed type __int64 __fastcall j__guard_check_icall_nop();
// 180003630: using guessed type _QWORD qword_180003630[2];

//----- (000000018000259C) ----------------------------------------------------
void __fastcall sub_18000259C()
{
  _QWORD *i; // rbx

  for ( i = &qword_180003640; i < &qword_180003640; ++i )
  {
    if ( *i )
      ((void (__fastcall *)(_QWORD))*i)(*i);
  }
}
// 1800025E8: using guessed type __int64 __fastcall j__guard_check_icall_nop();
// 180003640: using guessed type _QWORD qword_180003640;

//----- (0000000180002824) ----------------------------------------------------
char sub_180002824()
{
  return 1;
}

//----- (0000000180002828) ----------------------------------------------------
__int64 sub_180002828()
{
  return 0LL;
}

// nfuncs=72 queued=20 decompiled=20 lumina nreq=0 worse=0 better=0
// ALL OK, 20 function(s) have been successfully decompiled
